version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 032970428544.dkr.ecr.eu-west-1.amazonaws.com/clair-ecr-repo:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <your-ecr-registry>/<your-repository>:<tag>
      - docker push 032970428544.dkr.ecr.eu-west-1.amazonaws.com/clair-ecr-repo:latest
